// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOAKA4NSTow9slX9afGLZYFBRuRtYlRjE',
    appId: '1:537802064341:web:4d43de75a6dd8dbc283d5c',
    messagingSenderId: '537802064341',
    projectId: 'saarthi-cdbad',
    authDomain: 'saarthi-cdbad.firebaseapp.com',
    storageBucket: 'saarthi-cdbad.appspot.com',
    measurementId: 'G-FG5E3485R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVcjkzkVvMgMj21W5GZM6YbBrqnTxs30w',
    appId: '1:537802064341:android:1fa3ea9f069e1030283d5c',
    messagingSenderId: '537802064341',
    projectId: 'saarthi-cdbad',
    storageBucket: 'saarthi-cdbad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW-l2xY4URRuXAthpx53H1auxb3lMOk2A',
    appId: '1:537802064341:ios:370d0d7384892000283d5c',
    messagingSenderId: '537802064341',
    projectId: 'saarthi-cdbad',
    storageBucket: 'saarthi-cdbad.appspot.com',
    iosBundleId: 'com.example.saarthi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW-l2xY4URRuXAthpx53H1auxb3lMOk2A',
    appId: '1:537802064341:ios:370d0d7384892000283d5c',
    messagingSenderId: '537802064341',
    projectId: 'saarthi-cdbad',
    storageBucket: 'saarthi-cdbad.appspot.com',
    iosBundleId: 'com.example.saarthi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOAKA4NSTow9slX9afGLZYFBRuRtYlRjE',
    appId: '1:537802064341:web:c0350e1f9e0ccda7283d5c',
    messagingSenderId: '537802064341',
    projectId: 'saarthi-cdbad',
    authDomain: 'saarthi-cdbad.firebaseapp.com',
    storageBucket: 'saarthi-cdbad.appspot.com',
    measurementId: 'G-K4SXLQD2Y3',
  );
}
